version: '3'

services:
  fashion-mnist:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mongo
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: 27017
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: MLPlatform
    command: mongod --auth
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD